config/routes.rb
Micropost::Application.routes.draw do
  get "sessions/new"

  resources :mcroposts, :only => [:create, :destroy]
  resources :users do 
	  member do
		  get :following, :followers
	  end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]

match '/signin',  :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'
match '/contact', :to => 'pages#contact'
match '/about',   :to => 'pages#about'
match '/help',    :to => 'pages#help'
match '/signup',    :to => 'users#new'
root :to => 'pages#home'

end

app/models/mcropost.rb
class Mcropost < ActiveRecord::Base
	#validates :content, :length => { :maximum => 140 }
	attr_accessible :content
	belongs_to :user
	default_scope :order=>'mcroposts.created_at DESC'

	def self.from_users_followed_by(user)
		where(:user_id=>user.following.push(user))
	end

	scope :from_users_followed_by, lambda { |user| followed_by(user) }

	  private

	      # Return an SQL condition for users followed by the given user.
	  #     # We include the user's own id as well.
	  def self.followed_by(user)
	  #following_ids = user.following_ids
	  following_ids = %(SELECT followed_id FROM relationships
			                            WHERE follower_id = :user_id)
	  where("user_id IN (#{following_ids}) OR user_id = :user_id",
	  { :user_id => user })
	  end
end

app/controllers/mcroposts_controller.rb
class McropostsController < ApplicationController
	before_filter :authenticate, :only => [:create, :destroy]
	before_filter :authorized_user, :only => :destroy
  # GET /mcroposts
  # GET /mcroposts.json
  def index
    @mcroposts = Mcropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @mcroposts }
    end
  end

  # GET /mcroposts/1
  # GET /mcroposts/1.json
  def show
    @mcropost = Mcropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @mcropost }
    end
  end

  # GET /mcroposts/new
  # GET /mcroposts/new.json
  def new
    @mcropost = Mcropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @mcropost }
    end
  end

  # GET /mcroposts/1/edit
  def edit
    @mcropost = Mcropost.find(params[:id])
  end

  # POST /mcroposts
  # POST /mcroposts.json
  def create
    @mcropost = current_user.mcroposts.build(params[:mcropost])

    respond_to do |format|
      if @mcropost.save
	      flash[:success]="microposts created"
        #format.html { redirect_to @mcropost, :notice => 'Mcropost was successfully created.' }
        format.html { redirect_to root_path }
        format.json { render :json => @mcropost, :status => :created, :location => @mcropost }
      else
	      @feed_items=[]
        format.html { render 'pages/home' }
        format.json { render :json => @mcropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mcroposts/1
  # PUT /mcroposts/1.json
  def update
    @mcropost = Mcropost.find(params[:id])

    respond_to do |format|
      if @mcropost.update_attributes(params[:mcropost])
        format.html { redirect_to @mcropost, :notice => 'Mcropost was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @mcropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mcroposts/1
  # DELETE /mcroposts/1.json
  def destroy
    @mcropost = Mcropost.find(params[:id])
    @mcropost.destroy

    respond_to do |format|
      #format.html { redirect_to mcroposts_url }
      format.html { redirect_back_or root_path}
      format.json { head :ok }
    end
  end

private
     
def authorized_user
   @mcropost = current_user.mcroposts.find_by_id(params[:id])
     redirect_to root_path if @mcropost.nil?
end
end

app/helpers/mcroposts_helper.rb
module McropostsHelper
end

app/views/mcroposts/_form.html.erb
<%= form_for(@mcropost) do |f| %>
  <% if @mcropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mcropost.errors.count, "error") %> prohibited this mcropost from being saved:</h2>

      <ul>
      <% @mcropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mcroposts/_mcropost.html.erb
<tr>
<td class="micropost">
<span class="content"><%= mcropost.content %></span>
<span class="timestamp">
Posted <%= time_ago_in_words(mcropost.created_at) %> ago.
</span>
</td>
<% if current_user?(mcropost.user) %>
<td>
<%= link_to "delete", mcropost, :method => :delete, :confirm => "You sure?", :title => mcropost.content %>
</td>
<% end %>
</tr>

app/views/mcroposts/edit.html.erb
<h1>Editing mcropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @mcropost %> |
<%= link_to 'Back', mcroposts_path %>

app/views/mcroposts/index.html.erb
<h1>Listing mcroposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mcroposts.each do |mcropost| %>
  <tr>
    <td><%= mcropost.content %></td>
    <td><%= mcropost.user_id %></td>
    <td><%= link_to 'Show', mcropost %></td>
    <td><%= link_to 'Edit', edit_mcropost_path(mcropost) %></td>
    <td><%= link_to 'Destroy', mcropost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mcropost', new_mcropost_path %>

app/views/mcroposts/new.html.erb
<h1>New mcropost</h1>

<%= render 'form' %>

<%= link_to 'Back', mcroposts_path %>

app/views/mcroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @mcropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @mcropost.user_id %>
</p>


<%= link_to 'Edit', edit_mcropost_path(@mcropost) %> |
<%= link_to 'Back', mcroposts_path %>